db = {'host':'rds593f78790z8p64dz1.mysql.rds.aliyuncs.com',
      'port': 3306,
      'user':'lin',
      'passwd':'Qwert123',
      'database':'channel_chic_mini',
      'charset':'utf8'}

rqueue = {'host':'localhost',
           'port':'6379',
           'key':'ofashion'}

spiders = 'spiders' # spider路径

status_new = 'new'
status_failed = 'failed'
status_finished = 'finished'

unit_euro = 'EURO'
unit_jpy = 'JPY'
unit_hkd = 'HKD'
unit_rmb = 'RMB'
unit_usd = 'USD'

mapping = {'store.tods.cn': 'tods',
           'cn.vancleefarpels.com': 'vancleef',
           'www.omegawatches.cn': 'omega',
           'www.longines.cn': 'longines',
           'www.patek.com': 'patek',
           'www.vacheron-constantin.cn': 'constantin',
           'cn.jaeger-lecoultre.com': 'lecoultre',
           'www.panerai.cn': 'panerai',
           'www.iwc.com': 'iwc',
           'www.blancpain.com': 'blancpain',
           'www.audemarspiguet.com': 'audemarspiguet',
           'www.breguet.com': 'breguet',
           'www.chaumet.cn': 'chaumet',
           'www.tudorwatch.cn': 'tudor',
           'www.mikimoto.com.hk': 'mikimoto',
           'www.stellamccartney.cn': 'stellamccartney',
           'cn.boucheron.com': 'boucheron',
           'www.girard-perregaux.com': 'perregaux',
           'www.kenzoparfums.cn': 'kenzo',
           'www.loreal-paris.com.hk': 'loreal',
           'www.lancome.com.cn': 'lancome',
           'cn.chowsangsang.com': 'chowsangsang',
           'www.skii.com.cn': 'skii',
           'www.jeanrichard.com': 'jeanrichard',
           'www.ulysse-nardin.com': 'nardin',
           'cn.qeelin.com': 'qeelin',
           'www.pomellato.com': 'pomellato',
           'cn.puma.com': 'puma',
           'www.esteelauder.com.cn': 'esteelauder',
           'www.swarovski.com.cn': 'swarovski',
           'www.olay.com.cn': 'olay',
           'cn.ecco.com': 'ecco',
           'www.dhc.net.cn': 'dhc',
           'www.danielwellington.cn': 'danielwellington',
           'www.ysl.com': 'ysl',
           'www.gucci.cn': 'gucci',
           'www.bottegaveneta.com': 'bv',
           'china.elizabetharden.com': 'elizabetharden',
           'www.etro.com': 'etro',
           'cn.fresh.com': 'fresh',
           'www.fancl.com.cn': 'fancl',
           'www.guerlain.com.cn': 'guerlain',
           'www.giuseppezanotti.cn': 'giuseppezanotti',
           'www.hublot.cn': 'hublot',
           'www.helenarubinstein.cn': 'helenarubinstein',
           'www.hamiltonwatch.com': 'hamiltonwatch',
           'www.kanebo-global.com': 'kanebo',
           'www.isaknox.com.hk': 'isaknox',
           'www.innisfree.cn': 'innisfree',
           'www.freeplus.cn': 'freeplus',
           'www.lunasol-net.com': 'lunasol',
           'www.izzue.com': 'izzue',
           'www.jurlique.com.cn': 'jurlique',
           'www.kiehls.com.cn': 'kiehls',
           'sekkisei.kose.com.cn': 'kose',
           'store.moncler.cn': 'moncler',
           'www.hugoboss.cn': 'hugoboss',
           'cn.mcmworldwide.com': 'mcm',
           'www.harrywinston.cn': 'harrywinston',
           'www.arcteryx.com': 'arcteryx',
           'cn.sportmax.com': 'sportmax',
           'www.maje.cn': 'maje',
           'www.sandro-paris.cn': 'sandroparis',
           'www.pinko.com': 'pinko',
           'www.chopard.cn': 'chopard',
           'www.debeers.com.cn': 'debeers',
           'www.dsquared2.cn': 'dsquared2',
           'row.jimmychoo.com': 'jimmychoo',
           'www.banilaco.com.cn': 'banilaco',
           'www.chanel.com': 'chanel',
           'www.chanel.cn': 'chanel',
           'www.dior.cn': 'dior',
           'www.louisvuitton.cn': 'louisvuitton',
           'www.prada.com': 'prada',
           'cn.burberry.com': 'burberry',
           'store.balenciaga.cn': 'balenciaga',
           'www.cartier.cn': 'cartier',
           'www.tiffany.cn': 'tiffany',
           'store.dolcegabbana.com': 'dolcegabbana',
           'china.coach.com': 'coach',
           'www.valentino.cn': 'valentino',
           'www.chloe.cn': 'chloe',
           'www.acnestudios.com': 'acnestudios',
           'www.alexandermcqueen.cn': 'alexandermcqueen',
           'www.alexanderwang.cn': 'alexanderwang',
           'www.apm-monaco.cn': 'apmmonaco',
           # 'www.apm-monaco.cn': 'apm',
           'www.hermes.cn': 'hermes',
           'www.bally.cn': 'bally',
           'www.bobbibrown.com.cn': 'bobbibrown',
           'www.loewe.com': 'loewe',
           'www.michaelkors.cn': 'michaelkors',
           'www.ferragamo.cn': 'ferragamo',
           'www.stuartweitzman.cn': 'stuartweitzman'}
